modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/EchoEllet/shoulder-surfing-iron-spells-integration/issues/"

[[mods]]

modId = "${mod_id}"
version = "${mod_version}"
displayName = "Shoulder Surfing: Iron's Spells Integration"

displayURL = "https://github.com/EchoEllet/shoulder-surfing-iron-spells-integration"
logoFile="logo.png"

authors = "Ellet"
description = "Integrates Shoulder Surfing Reloaded with Iron’s Spells ’n Spellbooks, making the camera automatically follow your crosshair whenever you cast a spell—via spellbooks, normal spells, or quick cast. Compatible with controller mods."

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "irons_spellbooks"
type = "required"
versionRange = "${ironsSpellbooks_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "shouldersurfing"
type = "required"
versionRange = "${shouldersurfing_version_range}"
ordering = "NONE"
side = "BOTH"
